inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

# receiveとhave_receivedは挙動が大きく異なる(.and_returnを繋げられないなど)ため、
# receiveを許容する
RSpec/MessageSpies:
  Enabled: false

# 長さを優先して記述が分散すると逆に読みづらくなるため無効
RSpec/ExampleLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - "vendor/**/*"
